### ISSUE TITLE
replace unittest dependency by test

### ISSUE THREAD

**Issue by rspilker** [renggli/dart-junit#4] opened 2016-05-06 14:05 UTC
According to the [unittest documentation](https://pub.dartlang.org/packages/unittest) `unittest` has been deprecated and replaced by 'test'.

In my project I use `test` and cannot use `junitconfiguration` as a result :disappointed:

**Comment by renggli** [comment] 2016-05-06 15:55
I looked at this recently. The problem is that `test` does not support the necessary callbacks for a custom output format as provided by this package. We will have to see, if the file format could be integrated into the official package instead.

**Comment by renggli** [comment] 2021-04-06 07:47
Marking as obsolete, this package is no longer in use.

**Closed by renggli** 2021-04-06 07:47 UTC
